# Generated by Django 5.1.2 on 2024-10-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_borrowing_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='no',
        ),
    ]
